import {
  ProFormText,
  ProFormCaptcha,
  ProFormTextArea,
  ProFormDigit,
  ProFormDigitRange,
  ProFormDatePicker,
  ProFormDateTimePicker,
  ProFormDateRangePicker,
  ProFormDateTimeRangePicker,
  ProFormTimePicker,
  ProFormSelect,
  ProFormTreeSelect,
  ProFormCheckbox,
  ProFormRadio,
  ProFormCascader,
  ProFormSwitch,
  ProFormRate,
  ProFormSlider,
  ProFormUploadDragger,
  ProFormUploadButton,
  ProFormMoney,
  ProFormSegmented,
} from '@ant-design/pro-components';
// import ProFormUserSearchSelect from '@/father-pages/components/ProFormUserSearchSelect';
// import { ProFormWorkflowNameCascader } from '@/global-business-components';

export default {
  ProFormText,
  ProFormCaptcha,
  'ProFormText.Password': ProFormText.Password,
  ProFormTextArea,
  ProFormDigit,
  ProFormDigitRange,
  ProFormDatePicker,
  ProFormDateTimePicker,
  ProFormDateRangePicker,
  ProFormDateTimeRangePicker,
  ProFormTimePicker,
  ProFormSelect,
  ProFormTreeSelect,
  ProFormCheckbox,
  ProFormRadio: ProFormRadio.Group,
  ProFormCascader,
  ProFormSwitch,
  ProFormRate,
  ProFormSlider,
  ProFormUploadDragger,
  ProFormUploadButton,
  ProFormMoney,
  ProFormSegmented,
  // ProFormUserSearchSelect,
  // ProFormWorkflowNameCascader,
};
